/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a43f6354-3b3e-4e79-b21d-4fa421e90485",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ZVwdbS5rB",
    "aws_user_pools_web_client_id": "1f7iobn6tqkbjd0doautnvjkle",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://fmdpoofflbcidkctsktytfmr6u.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3j7p5p4dpzhthngpl2pal23yna",
    "aws_user_files_s3_bucket": "testbucket215429-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
